---
# MySQL Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "asdf"
        - name: MYSQL_DATABASE
          value: "student_management"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---
# ConfigMap for MySQL Initialization
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    USE student_management;
    
    CREATE TABLE IF NOT EXISTS students (
        id INT PRIMARY KEY AUTO_INCREMENT,
        student_id VARCHAR(20) UNIQUE NOT NULL,
        first_name VARCHAR(50) NOT NULL,
        last_name VARCHAR(50) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        phone VARCHAR(15),
        date_of_birth DATE,
        enrollment_date DATE DEFAULT (CURRENT_DATE),
        major VARCHAR(50),
        gpa DECIMAL(3,2),
        status ENUM('Active', 'Inactive', 'Graduated') DEFAULT 'Active',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
    
    INSERT INTO students (student_id, first_name, last_name, email, phone, date_of_birth, major, gpa, status) VALUES
    ('S001', 'John', 'Doe', 'john.doe@email.com', '1234567890', '2002-05-15', 'Computer Science', 3.75, 'Active'),
    ('S002', 'Jane', 'Smith', 'jane.smith@email.com', '9876543210', '2001-08-22', 'Mathematics', 3.92, 'Active'),
    ('S003', 'Mike', 'Johnson', 'mike.j@email.com', '5551234567', '2003-03-10', 'Physics', 3.45, 'Active')
    ON DUPLICATE KEY UPDATE student_id=student_id;

---
# Student App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
  labels:
    app: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: student-record-manager:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "student_management"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "asdf"
        stdin: true
        tty: true

---
# Student App Service (for potential web interface)
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
